import random as r

lista1 = ["Erõforrás-alapú megközelítéssel kell",
"Egy absztrakciós létra mentén kell",
"Alapvetõ fontosságú",
"Kiemelt projektünk",
"A menedzsment célja",
"Teljes összhangban kell",
"Belsõ kommunikáció révén kell",
"Csapatmunkában szükséges",
"Még ma szükséges",
"Nem tûr halasztást",
"Fontos lenne", 
"Szükséges lenne", 
"Szükséges", 
"Vállalatunk célja", 
"Kiemelt fontosságú feladat",
"Ennek szellemében kell",
"Formállogikai alapon kellene",
"Alkotó folyamat keretében kell",
"Felelõsséggel kell",
"A következõt kell tennünk:",
"Egyetlen megoldásunk van:",
"Az egyetlen kiút:",
"Tanácsadóink szerint célunk:",
"A menedzsment szeretné",
"Az üzletág szeretné",
"Most kell",
"Nincs más hátra, mint",
"Ne felejtsük el",
"Ne szalasszuk el",
"Szeretném",
"Célom",
"Az eddigiek szerint kell",
"A lényeg:",
"Feladatunk:",
"Küldetésünk:",
"A mai legfontosabb prioritás:",
"Megpróbáljuk",
"Megpróbálom",
"Megkíséreljük",
"Megkísérlem",
"Próbáljátok meg",
"Meg kell próbálnunk",
"Küldetésem",
"Új koncepció szerint kell",
"Azonnal szükséges",
"Egy megoldás van:",
"Kreatív módon kell",
"Sürgõsen szükséges",
"Személyes célom",
"Nincs más dolgunk, mint",
"Nincs más feladatom, mint",
"Legfontosabb feladatom",
"Legfontosabb küldetésem",
"Elsõdleges fontosságú lenne",
"Elengedhetetlen lenne",
"Létfontosságú dolog",
"Elengedhetetlenül fontos lenne",
"Itt az idõ",
"Nem halaszthatjuk el",
"Kreatív módon kell",
"Elemzések segítségével kell",
"Kreatív módon kéne",
"Látványosan kell",
"Minél feltûnõbben kell",
"Professzionális módon kell",
"Megfelelõ idõzítéssel kell"]

lista2 = ["implementálni", 
"átültetni",
"aggregálni", 
"aktívan menedzselni",
"aktiválni",
"allokálni", 
"analizálni", 
"áramvonalasítani", 
"arányosítani", 
"áthangszerelni", 
"átváltoztatni", 
"átvariálni", 
"átvezetni", 
"bátorítani",
"betanítani",
"befolyásolni", 
"benchmarkolni", 
"bevetni", 
"birtokba venni", 
"bõvíteni", 
"szûkíteni", 
"ellenõrizni", 
"elõmozdítani", 
"életre kelteni",
"facilitálni", 
"fejleszteni", 
"felnevelni", 
"felruházni", 
"felszabadítani", 
"forradalmasítani", 
"generálni", 
"hasznosítani", 
"hatékonyabbá tenni", 
"innovatívan fejleszteni", 
"integrálni", 
"iterálni", 
"kihangsúlyozni",
"kiválasztani",
"leválogatni", 
"leválasztani", 
"kihasználni",
"kiterjeszteni", 
"kultiválni", 
"lefoglalni", 
"lehetõvé tenni", 
"márkázni", 
"maximalizálni", 
"meghatározni", 
"megragadni", 
"megváltoztatni", 
"menedzselni", 
"monetizálni", 
"motiválni",
"növelni", 
"nyilvánvalóvá tenni", 
"optimalizálni", 
"ösztönözni", 
"kiépíteni", 
"rávilágítani",
"racionálisan végiggondolni",
"racionalizálni", 
"ritkítani",
"sûríteni",
"strategizálni", 
"struktúrálni", 
"szakmailag felügyelni", 
"szétszabdalni", 
"szimulálni",
"szindikálni", 
"szinergizálni", 
"szinkronba hozni", 
"sztenderdizálni",
"szintetizálni", 
"támogatni",
"targetálni", 
"termékesíteni", 
"testreszabni",
"toborozni",
"tipizálni",
"tiszta lappal kezdeni", 
"transzformálni", 
"túlteljesíteni", 
"új kontextusba helyezni", 
"újra feltalálni", 
"újra meghatározni", 
"újradefiniálni", 
"újrapozícionálni", 
"újratermelni", 
"vizionálni", 
"vizualizálni"]

lista3 = ["implementálni", 
"átültetni",
"aggregálni", 
"aktívan menedzselni",
"aktiválni",
"allokálni", 
"analizálni", 
"áramvonalasítani", 
"arányosítani", 
"áthangszerelni", 
"átváltoztatni", 
"átvariálni", 
"átvezetni", 
"bátorítani",
"betanítani",
"befolyásolni", 
"benchmarkolni", 
"bevetni", 
"birtokba venni", 
"bõvíteni", 
"szûkíteni", 
"ellenõrizni", 
"elõmozdítani", 
"életre kelteni",
"facilitálni", 
"fejleszteni", 
"felnevelni", 
"felruházni", 
"felszabadítani", 
"forradalmasítani", 
"generálni", 
"hasznosítani", 
"hatékonyabbá tenni", 
"innovatívan fejleszteni", 
"integrálni", 
"iterálni", 
"kihangsúlyozni",
"kiválasztani",
"leválogatni", 
"leválasztani", 
"kihasználni",
"kiterjeszteni", 
"kultiválni", 
"lefoglalni", 
"lehetõvé tenni", 
"márkázni", 
"maximalizálni", 
"meghatározni", 
"megragadni", 
"megváltoztatni", 
"menedzselni", 
"monetizálni", 
"motiválni",
"növelni", 
"nyilvánvalóvá tenni", 
"optimalizálni", 
"ösztönözni", 
"kiépíteni", 
"rávilágítani",
"racionálisan végiggondolni",
"racionalizálni", 
"ritkítani",
"sûríteni",
"strategizálni", 
"struktúrálni", 
"szakmailag felügyelni", 
"szétszabdalni", 
"szimulálni",
"szindikálni", 
"szinergizálni", 
"szinkronba hozni", 
"sztenderdizálni",
"szintetizálni", 
"támogatni",
"targetálni", 
"termékesíteni", 
"testreszabni",
"toborozni",
"tipizálni",
"tiszta lappal kezdeni", 
"transzformálni", 
"túlteljesíteni", 
"új kontextusba helyezni", 
"újra feltalálni", 
"újra meghatározni", 
"újradefiniálni", 
"újrapozícionálni", 
"újratermelni", 
"vizionálni", 
"vizualizálni"]

lista4 = ["implementálni", 
"átültetni",
"aggregálni", 
"aktívan menedzselni",
"aktiválni",
"allokálni", 
"analizálni", 
"áramvonalasítani", 
"arányosítani", 
"áthangszerelni", 
"átváltoztatni", 
"átvariálni", 
"átvezetni", 
"bátorítani",
"betanítani",
"befolyásolni", 
"benchmarkolni", 
"bevetni", 
"birtokba venni", 
"bõvíteni", 
"szûkíteni", 
"ellenõrizni", 
"elõmozdítani", 
"életre kelteni",
"facilitálni", 
"fejleszteni", 
"felnevelni", 
"felruházni", 
"felszabadítani", 
"forradalmasítani", 
"generálni", 
"hasznosítani", 
"hatékonyabbá tenni", 
"innovatívan fejleszteni", 
"integrálni", 
"iterálni", 
"kihangsúlyozni",
"kiválasztani",
"leválogatni", 
"leválasztani", 
"kihasználni",
"kiterjeszteni", 
"kultiválni", 
"lefoglalni", 
"lehetõvé tenni", 
"márkázni", 
"maximalizálni", 
"meghatározni", 
"megragadni", 
"megváltoztatni", 
"menedzselni", 
"monetizálni", 
"motiválni",
"növelni", 
"nyilvánvalóvá tenni", 
"optimalizálni", 
"ösztönözni", 
"kiépíteni", 
"rávilágítani",
"racionálisan végiggondolni",
"racionalizálni", 
"ritkítani",
"sûríteni",
"strategizálni", 
"struktúrálni", 
"szakmailag felügyelni", 
"szétszabdalni", 
"szimulálni",
"szindikálni", 
"szinergizálni", 
"szinkronba hozni", 
"sztenderdizálni",
"szintetizálni", 
"támogatni",
"targetálni", 
"termékesíteni", 
"testreszabni",
"toborozni",
"tipizálni",
"tiszta lappal kezdeni", 
"transzformálni", 
"túlteljesíteni", 
"új kontextusba helyezni", 
"újra feltalálni", 
"újra meghatározni", 
"újradefiniálni", 
"újrapozícionálni", 
"újratermelni", 
"vizionálni", 
"vizualizálni"]

def get_bullshit():
    return r.choice(lista1) + " " + r.choice(lista2) + " " + r.choice(lista3) + " " + r.choice(lista4) + "."